sudo: false
dist: trusty
language: node_js
node_js:
- 6.9.4
before_install:
- openssl aes-256-cbc -K $encrypted_acbf41d866e5_key -iv $encrypted_acbf41d866e5_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
install:
- npm install -g npm-check
- npm install
before_script:
- npm-check --skip-unused
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan klusbib.be >> ~/.ssh/known_hosts
- git remote add deploy dokku@klusbib.be:www
- git config --global push.default simple
- git push deploy master